### ISSUE TITLE
Make the site mobile/tablet responsive

### ISSUE THREAD

**Issue by chandan-reddy-k** [OpenSourceTogether/Hacktoberfest-2020#1]
Use CSS media queries and material UI breakpoints.

**Comment by daretobedifferent18** [comment]
I want to make the site mobile/tablet responsive.

**Comment by chandan-reddy-k** [comment]
Hey @daretobedifferent18 thanks for the help. The site is made using react and material-ui, so please make the changes and raise a PR if you’re comfortable working with them 😄.

**Comment by daretobedifferent18** [comment]
Pls help me out in running this project locally.

**Comment by chandan-reddy-k** [comment]
@daretobedifferent18 I'm planning for some re-design to the site. As a part of that, I'll cover the responsiveness issue too. So, closing this issue now. Please feel free to work on other issues in repo. 😃
