### ISSUE TITLE
Add your github profile in contributors.json

### ISSUE THREAD

**Issue by chandan-reddy-k** [OpenSourceTogether/Hacktoberfest-2020#2]

**Comment by debugleader** [comment]
Are you still active? @chandan-reddy-k

**Comment by chandan-reddy-k** [comment]
@debugleader yes

**Comment by debugleader** [comment]
Please check my PR @chandan-reddy-k

**Comment by daretobedifferent18** [comment]
Please check my PR @chandan-reddy-k

**Comment by RishiDharshan** [comment]
don it

**Comment by urjit2498** [comment]
Hey, @chandan-reddy-k please review my PR and merge in your repo. my id is @urjit2498

**Comment by aniketrb-github** [comment]
Hi  @chandan-reddy-k ,
please can you review and merge my [pull request](https://github.com/OpenSourceTogether/Hacktoberfest-2020/pull/119)? 
Thanks.

**Comment by PriyanshuSaini** [comment]
Hey! @chandan-reddy-k , Checkout my PR and merge it.
Thanks.

**Comment by garvitchittora** [comment]
Hi! @chandan-reddy-k  , Checkout my PR and merge it.
Thanks.

**Comment by abraaoduarte** [comment]
Please check my PR @chandan-reddy-k 
#226

**Comment by Smithaaaa** [comment]
hi can u plz check my pull request

**Comment by vaibhavtripathi1209** [comment]
is this pr count on hacktober fest

**Comment by satcasm** [comment]
Please review my pull request. #682

**Comment by chandan-reddy-k** [comment]
https://github.com/OpenSourceTogether/Hacktoberfest-2020/issues/146

**Comment by Swapnil074** [comment]
added  #770

**Comment by archisss** [comment]
This is counting or not for the Hacktoberfest 20202

**Comment by vinay72** [comment]
@chandan-reddy-k I've made a PR to this issue, please review and merge it.

**Comment by JullaEst** [comment]
Hello, I made a PR for this issue but how can I add a hacktoberfest label to make sure it counts?

**Comment by soumyjain14** [comment]
HOw to contribute in this?

**Comment by Dilshan97** [comment]
Please check out my PR #888

**Comment by vivekshotti** [comment]
@chandan-reddy-k , you still accepting?

**Comment by vivekshotti** [comment]
Please check my PR #1018

**Comment by szczepanieceryk** [comment]
Hi ! 
I've tried two times to add my profile and failed on 'Run schema check' , what's up with that ? 🤔

**Comment by Sukhija-Aniket** [comment]
is it assigned? can I try it now?
