### ISSUE TITLE
PRs won't count!!

### ISSUE THREAD

**Issue by Shwetago** [OpenSourceTogether/Hacktoberfest-2020#26]
I think you are spamming. Only those PRs will be counted which will be made between October 1st - October 31st.
You can specify in your Readme.

**Comment by chandan-reddy-k** [comment]
@Shwetago yes the dates are already in the readme. There is nothing to spam here. Moreover this repo is not yet complete, meaning I’m still working on making it mobile responsive and there is an issue for that too. Maybe it’s out of people’s own interest they are making the PRs now.

However your point is also valid when there is no point explicitly stating this. I’ll add this to the readme now. Feel free to open this issue incase of any problems.
